---
# Variables used by the "docker" role.
docker_apt_repository: "deb [arch={{ docker_apt_arch }}] {{ docker_repo_url }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
docker_repo_url: https://download.docker.com/linux
docker_apt_release_channel: stable
docker_apt_arch: amd64

docker_package: "docker-{{ docker_edition }}"
docker_edition: "ce"

docker_compose_url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
docker_compose_dest: /usr/local/bin/docker-compose
docker_compose_version: "1.26.0"