apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
  namespace: default
  labels:
    {{- include "app-python.labels" . | nindent 4 }}
data:
  config.json: |-
{{ .Files.Get "config.json" | indent 4 }}