apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "app-python.fullname" . }}
  labels:
    {{- include "app-python.labels" . | nindent 4 }}
spec:
  serviceName: "app-python"
  podManagementPolicy: "Parallel"
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app-python.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app-python.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: app-python-volume
              mountPath: "/app/files"
            - name: config-volume
              mountPath: "{{ .Values.config.mountPath }}"
              subPath: config.json
      volumes:
        - name: config-volume
          configMap:
            name: config-map
  volumeClaimTemplates:
    - metadata:
        name: app-python-volume
      spec:
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: {{ .Values.storageSize }}
