apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-python.fullname" . }}
  labels:
    {{- include "app-python.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "app-python.selectorLabels" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer