version: "3"  
services:  
  
  promtail:
    container_name: promtail_container
    image: grafana/promtail:2.3.0
    ports:
      - "9080:9080"
    networks:
      - monitoring_network
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./promtail/promtail.yml:/etc/promtail/promtail.yml
      - promtail-data:/var/lib/promtail/positions
    command: 
      - '--config.file=/etc/promtail/promtail.yml'
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "20m" 
        max-file: "10"
        tag: "{{ .ImageName }}|{{ .Name }}"
    mem_limit: "512m"
    mem_reservation: "128m"
    
  grafana:
    container_name: grafana_container
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - monitoring_network
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    env_file:
      - ./grafana/config.monitoring
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "20m" 
        max-file: "10"
        tag: "{{ .ImageName }}|{{ .Name }}"
    mem_limit: "512m"
    mem_reservation: "128m"

  loki:
    container_name: loki_container
    image: grafana/loki:2.3.0
    user: root
    ports:
      - "3100:3100"
    networks:
      - monitoring_network
    volumes:
      - ./loki/loki.yml:/etc/loki/local-config.yml
      - loki-data:/tmp/loki/
    command: 
      - '--config.file=/etc/loki/local-config.yml'
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "20m" 
        max-file: "10"
        tag: "{{ .ImageName }}|{{ .Name }}"
    mem_limit: "512m"
    mem_reservation: "128m"

  app:
    container_name: app_container
    image: marinasmirnova/devops:latest
    ports:
      - "5000:5000"
    networks:
      - monitoring_network
    volumes:
      - /sys/fs/cgroup/memory/docker:/docker/memory
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_API_VERSION=1.41
    logging:
      driver: "json-file"
      options:
        max-size: "20m" 
        max-file: "10"
        tag: "{{ .ImageName }}|{{ .Name }}"
    mem_limit: "512m"
    mem_reservation: "128m"

  prometheus:
    container_name: prometheus_container
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - monitoring_network
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    logging:
      driver: "json-file"
      options:
        max-size: "20m" 
        max-file: "10"
        tag: "{{ .ImageName }}|{{ .Name }}"
    mem_limit: "512m"
    mem_reservation: "128m"


networks:
  monitoring_network:
    name: monitoring_network
    driver: bridge
    ipam:
      driver: default

volumes:
  promtail-data: {}
  grafana-data: {}
  loki-data: {}
  prometheus-data: {}